# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orchestrator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'orchestrator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12orchestrator.proto\x12\x0corchestrator\"_\n\x0bTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x11\n\ttask_type\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\t\x12\x1b\n\x13required_capability\x18\x04 \x01(\t\"N\n\x0cTaskResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t\"\"\n\rHealthRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\"_\n\x0eHealthResponse\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\r\n\x05\x61live\x18\x02 \x01(\x08\x12\x13\n\x0b\x63pu_percent\x18\x03 \x01(\x01\x12\x16\n\x0ememory_percent\x18\x04 \x01(\x01\x32\x9b\x01\n\rWorkerService\x12@\n\x07RunTask\x12\x19.orchestrator.TaskRequest\x1a\x1a.orchestrator.TaskResponse\x12H\n\x0bHealthCheck\x12\x1b.orchestrator.HealthRequest\x1a\x1c.orchestrator.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orchestrator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKREQUEST']._serialized_start=36
  _globals['_TASKREQUEST']._serialized_end=131
  _globals['_TASKRESPONSE']._serialized_start=133
  _globals['_TASKRESPONSE']._serialized_end=211
  _globals['_HEALTHREQUEST']._serialized_start=213
  _globals['_HEALTHREQUEST']._serialized_end=247
  _globals['_HEALTHRESPONSE']._serialized_start=249
  _globals['_HEALTHRESPONSE']._serialized_end=344
  _globals['_WORKERSERVICE']._serialized_start=347
  _globals['_WORKERSERVICE']._serialized_end=502
# @@protoc_insertion_point(module_scope)
